/**
 * @file src/admin/marketingHelpData.ts
 * @description Comprehensive 11-point contextual help definitions for Phase 19 Marketing Automation, RFM Segmentation, CRM & Referral Engine
 * @license Apache-2.0
 */

import { AdminFunctionHelpData } from '../components/admin/AdminHelpModal';

export const MARKETING_HELP_DATA: Record<string, AdminFunctionHelpData> = {
  RFM_SEGMENTATION: {
    id: 'RFM_SEGMENTATION',
    title: 'RFM (Recency, Frequency, Monetary) Customer Segmentation Matrix',
    titleBn: 'আরএফএম (সাম্প্রতিকতা, পুনরাবৃত্তি ও আর্থিক মূল্য) কাস্টমার সেগমেন্টেশন ম্যাট্রিক্স',
    whatIsThis: 'A data-driven behavioral framework that classifies buyers into 7 strategic cohorts based on days since last purchase (Recency), total order count (Frequency), and cumulative lifetime spend in BDT (Monetary).',
    whatIsThisBn: 'একটি ডেটা-চালিত আচরণগত ফ্রেমওয়ার্ক যা গ্রাহকদের শেষ ক্রয়ের দিন (Recency), মোট অর্ডারের সংখ্যা (Frequency) এবং মোট খরচের (Monetary) ওপর ভিত্তি করে ৭টি কৌশলগত ক্যাটাগরিতে বিভক্ত করে।',
    whyUsed: 'Prevents wasteful blanket mass-messaging by allowing marketing teams to target high-value VIPs, retain loyal repeat buyers, re-engage churn risks, and nurture first-time shoppers with tailored incentives.',
    whyUsedBn: 'সকলকে একই বার্তা পাঠানোর অপচয় বন্ধ করে এবং ভিআইপি, বিশ্বস্ত ক্রেতা, ঝুঁকিপূর্ণ গ্রাহক ও নতুন ক্রেতাদের জন্য সুনির্দিষ্ট অফার ও যোগাযোগ নিশ্চিত করে।',
    howItWorks: 'The server analyzes historical customer orders, scores R, F, and M on a 1-to-5 scale, and assigns an automated cohort with tailored action recommendations.',
    howItWorksBn: 'সার্ভার গ্রাহকদের অতীত অর্ডার ইতিহাস বিশ্লেষণ করে ১ থেকে ৫ স্কেলে স্কোর নির্ধারণ করে এবং উপযুক্ত মার্কেটিং সুপারিশসহ সেগমেন্ট প্রস্তুত করে।',
    connectedTo: ['Customer Profiles', 'Orders Database', 'SMS & WhatsApp Gateway', 'Promotion Engine'],
    connectedToBn: ['গ্রাহক প্রোফাইল', 'অর্ডার ডাটাবেজ', 'এসএমএস ও হোয়াটসঅ্যাপ গেটওয়ে', 'প্রমোশন ইঞ্জিন'],
    whatHappensIfChanged: 'New customer orders dynamically adjust the cohort membership in real-time.',
    whatHappensIfChangedBn: 'নতুন যেকোনো অর্ডারের সাথে সাথে গ্রাহকের সেগমেন্ট রিয়েল-টাইমে স্বয়ংক্রিয়ভাবে হালনাগাদ হয়।',
    affects: ['Targeted marketing campaigns', 'Audience sizing', 'Promotional ROI', 'Discount budget allocation'],
    affectsBn: ['টার্গেটেড মার্কেটিং ক্যাম্পেইন', 'অডিয়েন্সের আকার', 'প্রমোশনাল আরওআই', 'ডিসকাউন্ট বাজেট'],
    doesNotAffect: ['Actual customer bank accounts', 'Courier booking APIs', 'Product retail prices'],
    doesNotAffectBn: ['গ্রাহকের ব্যাংক হিসাব', 'কুরিয়ার বুকিং এপিআই', 'পণ্যের সাধারণ বিক্রয়মূল্য'],
    requirements: ['Accurate order history linked by verified customer mobile number'],
    requirementsBn: ['যাচাইকৃত মোবাইল নম্বরের সাথে যুক্ত সঠিক অর্ডার হিস্ট্রি'],
    currentStatus: 'Active real-time algorithmic calculation',
    currentStatusBn: 'রিয়েল-টাইম অ্যালগরিদমিক ক্যালকুলেশন সক্রিয়',
    riskLevel: 'LOW',
    riskWarning: 'Ensure customer phone numbers are stored in normalized E.164 (+880...) format to prevent split profiles.',
    riskWarningBn: 'গ্রাহকের ফোন নম্বর সবসময় স্ট্যান্ডার্ড (+৮৮০...) ফরম্যাটে রাখুন যাতে একই গ্রাহকের একাধিক প্রোফাইল তৈরি না হয়।',
    whoCanChange: 'Super Admin, Marketing Lead, CRM Manager',
    whoCanChangeBn: 'সুপার অ্যাডমিন, মার্কেটিং প্রধান, সিআরএম ম্যানেজার'
  },

  CHAMPIONS_VIP: {
    id: 'CHAMPIONS_VIP',
    title: 'Champions & VIP Buyer Tier',
    titleBn: 'চ্যাম্পিয়ন ও ভিআইপি গ্রাহক ক্যাটাগরি',
    whatIsThis: 'High-affinity customers who buy frequently, spend substantial amounts (BDT 10,000+), and have ordered within the last 30 days.',
    whatIsThisBn: 'কিশলয়ের শীর্ষস্থানীয় গ্রাহক যারা নিয়মিত কেনাকাটা করেন, উল্লেখযোগ্য পরিমাণ (১০,০০০+ টাকা) খরচ করেছেন এবং গত ৩০ দিনের মধ্যে সক্রিয় ছিলেন।',
    whyUsed: 'VIP customers typically contribute 40-60% of total revenue. Nurturing them guarantees brand advocacy and sustainable organic growth.',
    whyUsedBn: 'ভিআইপি গ্রাহকরা মোট বিক্রয়ের একটি বিশাল অংশ যোগান দেন। তাদের সন্তুষ্টি ধরে রাখা ব্র্যান্ডের স্থায়ী প্রবৃদ্ধির মূল চাবিকাঠি।',
    howItWorks: 'Criteria: Recency <= 30 days, Frequency >= 3 orders, Monetary >= BDT 8,000.',
    howItWorksBn: 'শর্তাবলি: শেষ অর্ডার ৩০ দিনের মধ্যে, অর্ডার সংখ্যা ন্যূনতম ৩টি এবং মোট খরচ ৮,০০০+ টাকা।',
    connectedTo: ['Loyalty Point Multipliers', 'Exclusive Heritage Previews', 'Concierge Support'],
    connectedToBn: ['লয়্যালটি পয়েন্ট মাল্টিপ্লায়ার', 'এক্সক্লুসিভ কালেকশন প্রিভিউ', 'বিশেষ সাপোর্ট ডেস্ক'],
    whatHappensIfChanged: 'Inactivity past 60 days causes automatic transition to "Potential Loyalist" or "At-Risk".',
    whatHappensIfChangedBn: '৬০ দিনের বেশি সময় নিষ্ক্রিয় থাকলে গ্রাহক স্বয়ংক্রিয়ভাবে অন্য সেগমেন্টে স্থানান্তরিত হন।',
    affects: ['Priority order packaging', 'VIP campaign lists', 'Early flash-sale access'],
    affectsBn: ['অগ্রাধিকারমূলক প্যাকিং', 'ভিআইপি ক্যাম্পেইন তালিকা', 'আগাম কেনাকাটার সুযোগ'],
    doesNotAffect: ['Standard courier SLA fees', 'Website public pricing'],
    doesNotAffectBn: ['সাধারণ কুরিয়ার ফি', 'ওয়েবসাইটের উন্মুক্ত মূল্য'],
    requirements: ['Verified contact details and completed delivery confirmation'],
    requirementsBn: ['যাচাইকৃত যোগাযোগ নম্বর এবং সফল ডেলিভারি রেকর্ড'],
    currentStatus: 'Monitoring active VIP patrons',
    currentStatusBn: 'সক্রিয় ভিআইপি গ্রাহকদের পর্যবেক্ষণ করা হচ্ছে',
    riskLevel: 'LOW',
    riskWarning: 'Never send spam or low-value bulk messages to VIPs; preserve high brand prestige.',
    riskWarningBn: 'ভিআইপি গ্রাহকদের অপ্রয়োজনীয় বাল্ক বার্তা পাঠাবেন না; ব্র্যান্ডের ভাবমূর্তি বজায় রাখুন।',
    whoCanChange: 'CRM Operations Lead',
    whoCanChangeBn: 'সিআরএম অপারেশন প্রধান'
  },

  AT_RISK_CUSTOMERS: {
    id: 'AT_RISK_CUSTOMERS',
    title: 'At-Risk / Churn Prevention Cohort',
    titleBn: 'ঝুঁকিপূর্ণ / হারিয়ে যেতে বসা গ্রাহক সেগমেন্ট',
    whatIsThis: 'Previously loyal or multi-order customers who have not placed a purchase in over 60 to 120 days.',
    whatIsThisBn: 'পূর্বে একাধিক অর্ডার করা সম্মানিত ক্রেতা যারা গত ৬০ থেকে ১২০ দিন যাবৎ কোনো নতুন অর্ডার করেননি।',
    whyUsed: 'Acquiring a new customer is 5x more costly in Bangladesh than retaining an existing one. Re-engaging this group recaptures lost GMV.',
    whyUsedBn: 'বাংলাদেশে নতুন গ্রাহক সংগ্রহের চেয়ে পুরাতন গ্রাহক ফিরিয়ে আনা ৫ গুণ বেশি সাশ্রয়ী। এই সেগমেন্ট হারানো বিক্রয় পুনরুদ্ধারে সাহায্য করে।',
    howItWorks: 'Filters customers with Frequency >= 2 whose Recency is between 60 and 120 days. Suggests automated comeback incentives.',
    howItWorksBn: 'নূন্যতম ২টি অর্ডার করা গ্রাহকদের মধ্যে যাদের শেষ ক্রয়ের ব্যবধান ৬০-১২০ দিন, তাদের জন্য উইন-ব্যাক অফার তৈরি করে।',
    connectedTo: ['Win-Back SMS Automation', 'Dynamic Comeback Coupons', 'Customer Retention Metric'],
    connectedToBn: ['উইন-ব্যাক এসএমএস অটোমেশন', 'স্পেশাল রি-অ্যাক্টিভেশন কুপন', 'কাস্টমার রিটেনশন মেট্রিক'],
    whatHappensIfChanged: 'Placing a successful order immediately graduates the customer back to "Loyal" status.',
    whatHappensIfChangedBn: 'নতুন একটি অর্ডার সফল হলে গ্রাহক তাৎক্ষণিকভাবে পুনরায় "লয়্যাল" তালিকায় ফিরে যান।',
    affects: ['Re-activation campaign dispatch lists', 'Churn rate calculation'],
    affectsBn: ['রি-অ্যাক্টিভেশন ক্যাম্পেইন তালিকা', 'গ্রাহক হারানোর হার হিসাব'],
    doesNotAffect: ['Order fulfillment workflows', 'Product inventory counts'],
    doesNotAffectBn: ['অর্ডার ফুলফিলমেন্ট প্রক্রিয়া', 'পণ্যের মজুদ সংখ্যা'],
    requirements: ['Valid phone number opted-in to receive promotional updates'],
    requirementsBn: ['প্রমোশনাল আপডেট গ্রহণে সম্মত বৈধ ফোন নম্বর'],
    currentStatus: 'Active churn monitoring',
    currentStatusBn: 'সক্রিয় পর্যবেক্ষণ চলছে',
    riskLevel: 'MEDIUM',
    riskWarning: 'Do not discount too steeply to avoid training customers to wait for discounts before ordering.',
    riskWarningBn: 'অতিরিক্ত ছাড় দেবেন না যাতে গ্রাহকরা স্বাভাবিক কেনাকাটা বন্ধ করে শুধু ছাড়ের জন্য অপেক্ষা না করেন।',
    whoCanChange: 'Marketing Director, CRM Specialist',
    whoCanChangeBn: 'মার্কেটিং পরিচালক, সিআরএম স্পেশালিস্ট'
  },

  ABANDONED_CART_RECOVERY: {
    id: 'ABANDONED_CART_RECOVERY',
    title: 'Abandoned Cart Automated Recovery Engine',
    titleBn: 'পরিত্যক্ত কার্ট স্বয়ংক্রিয় পুনরুদ্ধার ইঞ্জিন',
    whatIsThis: 'An automated tracking and multi-stage re-engagement engine that captures shopper sessions where items were added to cart but checkout was not completed.',
    whatIsThisBn: 'একটি স্বয়ংক্রিয় ট্র্যাকিং ও যোগাযোগ ইঞ্জিন যা কার্টে পণ্য যোগ করেও চেকআউট সম্পন্ন না করা ক্রেতাদের সেশন শনাক্ত ও পুনরুদ্ধার করে।',
    whyUsed: 'In Bangladesh e-commerce, 65-75% of carts are abandoned due to payment gateway timeouts, hesitation over delivery charge, or interruptions. Automated nudges recover 15-25% of this revenue.',
    whyUsedBn: 'বাংলাদেশে পেমেন্ট গেটওয়ে জটিলতা বা দ্বিধাদ্বন্দ্বের কারণে প্রায় ৬৫-৭৫% কার্ট পরিত্যক্ত হয়। সময়মতো রিমাইন্ডার পাঠিয়ে এর ১৫-২৫% পুনরুদ্ধার সম্ভব।',
    howItWorks: 'Tracks drop-off step (Cart, Shipping, Payment, Gateway), logs session tokens, and executes recovery stages with direct 1-click cart restoration links.',
    howItWorksBn: 'ড্রপ-অফ স্তর পর্যবেক্ষণ করে নিরাপদ কার্ট লিঙ্ক তৈরি করে এবং এসএমএস/হোয়াটসঅ্যাপের মাধ্যমে ১-ক্লিকে চেকআউটের সুযোগ দেয়।',
    connectedTo: ['Checkout Session State', 'SMS Gateway', 'WhatsApp Business API', 'Coupon Engine'],
    connectedToBn: ['চেকআউট সেশন স্টেট', 'এসএমএস গেটওয়ে', 'হোয়াটসঅ্যাপ বিজনেস এপিআই', 'কুপন ইঞ্জিন'],
    whatHappensIfChanged: 'Triggering a nudge sends an SMS or WhatsApp notification to the customer with an incentive coupon and direct checkout link.',
    whatHappensIfChangedBn: 'রিকভারি ট্রিগার করলে গ্রাহকের কাছে কুপন কোড ও সরাসরি চেকআউট লিঙ্কসহ মেসেজ পৌঁছে যায়।',
    affects: ['Customer checkout conversion rate', 'Recovered GMV', 'SMS gateway costs'],
    affectsBn: ['চেকআউট কনভার্সন রেট', 'পুনরুদ্ধারকৃত বিক্রয়', 'এসএমএস গেটওয়ে খরচ'],
    doesNotAffect: ['Existing confirmed orders', 'Delivered shipment records'],
    doesNotAffectBn: ['পূর্ববর্তী নিশ্চিত অর্ডার', 'ডেলিভারিকৃত চালান'],
    requirements: ['Customer phone number captured during checkout attempt', 'Active SMS/WhatsApp credentials'],
    requirementsBn: ['চেকআউটে সংগৃহীত মোবাইল নম্বর', 'সক্রিয় এসএমএস/হোয়াটসঅ্যাপ গেটওয়ে'],
    currentStatus: 'Operational real-time recovery tracker',
    currentStatusBn: 'রিয়েল-টাইম রিকভারি ট্র্যাকার সক্রিয়',
    riskLevel: 'LOW',
    riskWarning: 'Do not send more than 3 recovery messages to avoid customer annoyance and telecom spam penalties.',
    riskWarningBn: 'বিরক্তিকর বার্তা এড়াতে একই কার্টের জন্য ৩টির বেশি রিমাইন্ডার পাঠাবেন না।',
    whoCanChange: 'Super Admin, Operations Lead, Marketing Manager',
    whoCanChangeBn: 'সুপার অ্যাডমিন, অপারেশন প্রধান, মার্কেটিং ম্যানেজার'
  },

  REFERRAL_PROGRAM_CONFIG: {
    id: 'REFERRAL_PROGRAM_CONFIG',
    title: 'Referral & Advocate Incentive Rules',
    titleBn: 'রেফারেল ও ব্র্যান্ড অ্যাডভোকেট রিওয়ার্ড নীতিমালা',
    whatIsThis: 'Configurable business rules defining the double-sided reward structure when an existing patron invites a new buyer to Kisholoy.',
    whatIsThisBn: 'বিদ্যমান গ্রাহক অন্য কাউকে কিশলয়ে কেনাকাটার জন্য আমন্ত্রণ জানালে উভয় পক্ষের জন্য নির্ধারিত দ্বিমুখী পুরস্কার নীতিমালা।',
    whyUsed: 'Word-of-mouth referral is the lowest Customer Acquisition Cost (CAC) marketing channel in Bangladesh.',
    whyUsedBn: 'পরিচিতজনদের মাধ্যমে রেফারেল হলো বাংলাদেশে সবচেয়ে কম খরচে নতুন ও বিশ্বাসযোগ্য ক্রেতা অর্জনের সেরা মাধ্যম।',
    howItWorks: 'The referee gets an immediate discount on their first qualified order (e.g. ৳100 off on ৳1,200+). Upon successful delivery, the referrer automatically receives store credit (e.g. ৳150) in their wallet.',
    howItWorksBn: 'নতুন ক্রেতা প্রথম অর্ডারে ছাড় পান এবং পণ্যটি সফলভাবে ডেলিভারি হওয়ার পর আমন্ত্রক তার ওয়ালেটে সরাসরি স্টোর ক্রেডিট বা লয়্যালটি বোনাস পান।',
    connectedTo: ['Customer Loyalty Wallets', 'Checkout Discount Calculation', 'Audit Trail', 'Fraud Engine'],
    connectedToBn: ['কাস্টমার লয়্যালটি ওয়ালেট', 'চেকআউট ডিসকাউন্ট ক্যালকুলেশন', 'অডিট ট্রেইল', 'ফ্রড ইঞ্জিন'],
    whatHappensIfChanged: 'Modifications apply immediately to all newly generated referral links and prospective orders.',
    whatHappensIfChangedBn: 'পরিবর্তনগুলো তাৎক্ষণিকভাবে নতুন তৈরি রেফারেল লিঙ্ক ও ভবিষ্যৎ অর্ডারের ক্ষেত্রে কার্যকর হয়।',
    affects: ['Referral reward amounts', 'Eligibility thresholds', 'Loyalty wallet credits'],
    affectsBn: ['রেফারেল পুরস্কারের পরিমাণ', 'ন্যূনতম অর্ডারের শর্ত', 'লয়্যালটি ওয়ালেট ক্রেডিট'],
    doesNotAffect: ['Past rewarded transactions', 'Non-referral regular coupons'],
    doesNotAffectBn: ['অতীতের সমাপ্ত রেফারেল লেনদেন', 'সাধারণ প্রোমো কোড'],
    requirements: ['Referral program toggled active', 'Sufficient operating promotional budget'],
    requirementsBn: ['রেফারেল প্রোগ্রাম সক্রিয় থাকা', 'যথাযথ প্রমোশনাল বাজেট বরাদ্দ'],
    currentStatus: 'Double-sided reward engine enabled',
    currentStatusBn: 'দ্বিমুখী রিওয়ার্ড ইঞ্জিন সক্রিয়',
    riskLevel: 'MEDIUM',
    riskWarning: 'Keep referee minimum order value sufficiently above the discount amount to prevent margin leakage.',
    riskWarningBn: 'ন্যূনতম অর্ডারের সীমা সবসময় ছাড়ের পরিমাণের চেয়ে যথেষ্ট উঁচুতে রাখুন যাতে ব্যবসায় ক্ষতি না হয়।',
    whoCanChange: 'Super Admin, Marketing Director',
    whoCanChangeBn: 'সুপার অ্যাডমিন, মার্কেটিং পরিচালক'
  },

  ANTI_FRAUD_SELF_REFERRAL: {
    id: 'ANTI_FRAUD_SELF_REFERRAL',
    title: 'Referral Abuse & Self-Referral Prevention Rule',
    titleBn: 'রেফারেল অপব্যবহার ও সেলফ-রেফারেল প্রতিরোধ নীতি',
    whatIsThis: 'Automated cryptographic and pattern-matching validation verifying that the referrer and referee are distinct individuals.',
    whatIsThisBn: 'স্বয়ংক্রিয় যাচাইকরণ ব্যবস্থা যা নিশ্চিত করে যে আমন্ত্রক এবং নতুন ক্রেতা সম্পূর্ণ আলাদা ব্যক্তি।',
    whyUsed: 'Prevents rogue users from creating disposable alternate accounts with the same phone, IP, or delivery address solely to farm referral bonuses.',
    whyUsedBn: 'একই ব্যক্তি যেন নিজের দ্বিতীয় ফোন নম্বর বা ভুয়া অ্যাকাউন্ট ব্যবহার করে অনৈতিকভাবে রেফারেল বোনাস হাতিয়ে নিতে না পারে।',
    howItWorks: 'Inspects normalized mobile phone numbers, client IP subnets, device footprints, and shipping addresses. Rejects self-referrals with detailed audit flags.',
    howItWorksBn: 'মোবাইল নম্বর, আইপি সাবনেট এবং ডেলিভারি ঠিকানা স্ক্যান করে কোনো মিল পাওয়া গেলে রেফারেল বাতিল ও ফ্ল্যাগ করে।',
    connectedTo: ['Fraud & Anti-Abuse Dashboard', 'Referral Ledger', 'Customer Blacklist'],
    connectedToBn: ['ফ্রড ও অ্যান্টি-অ্যাবিউজ ড্যাশবোর্ড', 'রেফারেল লেজার', 'কাস্টমার ব্ল্যাকলিস্ট'],
    whatHappensIfChanged: 'Disabling this setting exposes the store to bonus exploitation and artificial credit drain.',
    whatHappensIfChangedBn: 'এই নিরাপত্তা বন্ধ করলে অসদুপায়ে বোনাস হাতিয়ে নেওয়ার ঝুঁকি তৈরি হবে।',
    affects: ['Referral qualification status', 'Reward disbursement blockage', 'Risk scoring'],
    affectsBn: ['রেফারেল যোগ্যতার স্ট্যাটাস', 'রিওয়ার্ড প্রদান স্থগিতকরণ', 'রিস্ক স্কোরিং'],
    doesNotAffect: ['Legitimate non-related referrals', 'General store catalog browsing'],
    doesNotAffectBn: ['বৈধ সাধারণ রেফারেল', 'সাধারণ পণ্য ব্রাউজিং'],
    requirements: ['Unique phone numbers required for all checkout transactions'],
    requirementsBn: ['প্রতিটি কেনাকাটায় ইউনিক ফোন নম্বর থাকা আবশ্যক'],
    currentStatus: 'Enforced automatically on all referral operations',
    currentStatusBn: 'সকল রেফারেল কার্যক্রমে স্বয়ংক্রিয়ভাবে বলবৎ',
    riskLevel: 'HIGH',
    riskWarning: 'Do NOT disable self-referral protection in production environments.',
    riskWarningBn: 'প্রোডাকশন এনভায়রনমেন্টে এই নিরাপত্তা নিয়ন্ত্রণ কখনো নিষ্ক্রিয় করবেন না।',
    whoCanChange: 'Super Admin only',
    whoCanChangeBn: 'শুধুমাত্র সুপার অ্যাডমিন'
  },

  CAMPAIGN_BROADCAST_HUB: {
    id: 'CAMPAIGN_BROADCAST_HUB',
    title: 'Multi-Channel Marketing Campaign Scheduler',
    titleBn: 'মাল্টি-চ্যানেল মার্কেটিং ক্যাম্পেইন ও শিডিউলার',
    whatIsThis: 'A centralized communication console to compose, preview, schedule, and broadcast targeted SMS, WhatsApp, and Email campaigns to specific customer segments.',
    whatIsThisBn: 'একটি কেন্দ্রীভূত কন্ট্রোল প্যানেল যেখান থেকে নির্দিষ্ট গ্রাহক সেগমেন্টের জন্য এসএমএস, হোয়াটসঅ্যাপ ও ইমেইল ক্যাম্পেইন তৈরি, প্রিভিউ এবং প্রচার করা যায়।',
    whyUsed: 'Allows timely festival announcements (Pohela Boishakh, Eid, Puja), new handloom arrival alerts, and flash-sale countdowns with measured ROI.',
    whyUsedBn: 'পহেলা বৈশাখ, ঈদ বা পূজার মতো উৎসবগুলোতে নির্দিষ্ট কালেকশনের খবর দ্রুত ক্রেতাদের কাছে পৌঁছে দিয়ে বিক্রয় বহুগুণ বৃদ্ধি করে।',
    howItWorks: 'Connects to Bangladesh telecom SMS routes and WhatsApp Business APIs. Calculates GSM 7-bit / Unicode Bangla message lengths and tracks attribution.',
    howItWorksBn: 'বাংলা ইউনিকোড অক্ষর গণনা করে টেলিকম এগ্রিগেটর গেটওয়ের মাধ্যমে সঠিক অডিয়েন্সের কাছে বার্তা প্রেরণ করে এবং কনভার্সন ট্র্যাক করে।',
    connectedTo: ['SMS Gateway Adapters', 'WhatsApp Cloud API', 'Customer Segments', 'Financial P&L'],
    connectedToBn: ['এসএমএস গেটওয়ে অ্যাডাপ্টার', 'হোয়াটসঅ্যাপ ক্লাউড এপিআই', 'কাস্টমার সেগমেন্ট', 'ফাইন্যান্সিয়াল পিঅ্যান্ডএল'],
    whatHappensIfChanged: 'Executing a campaign dispatches messages immediately and updates live audience delivery and revenue metrics.',
    whatHappensIfChangedBn: 'ক্যাম্পেইন রান করলে তাৎক্ষণিকভাবে বার্তা চলে যায় এবং ডেলিভারি ও বিক্রয়ের হিসাব আপডেট হয়।',
    affects: ['Storefront traffic spikes', 'Customer inbox communications', 'Promotional expense'],
    affectsBn: ['ওয়েবসাইটে ভিজিটরের চাপ', 'গ্রাহকের ইনবক্স নোটিফিকেশন', 'মার্কেটিং খরচ'],
    doesNotAffect: ['Stock availability until orders are actually placed', 'Courier fees'],
    doesNotAffectBn: ['অর্ডার না হওয়া পর্যন্ত পণ্যের স্টক', 'কুরিয়ার চার্জ'],
    requirements: ['SMS gateway balance / WhatsApp API token', 'Target segment audience >= 1'],
    requirementsBn: ['এসএমএস ব্যালেন্স বা হোয়াটসঅ্যাপ টোকেন', 'টার্গেট সেগমেন্টে গ্রাহক থাকা'],
    currentStatus: 'Ready for scheduled and instant dispatch',
    currentStatusBn: 'তাত্ক্ষণিক ও শিডিউলড প্রচারের জন্য প্রস্তুত',
    riskLevel: 'MEDIUM',
    riskWarning: 'Double check character counts and Bangla unicode rendering before blasting thousands of SMS.',
    riskWarningBn: 'হাজার হাজার এসএমএস পাঠানোর আগে বাংলা ইউনিকোড ফরম্যাটিং ও অক্ষরের সংখ্যা ভালোভাবে যাচাই করুন।',
    whoCanChange: 'Super Admin, Marketing Director',
    whoCanChangeBn: 'সুপার অ্যাডমিন, মার্কেটিং পরিচালক'
  },

  CUSTOMER_CRM_360: {
    id: 'CUSTOMER_CRM_360',
    title: 'Customer 360° CRM Intelligence & Tagging',
    titleBn: 'কাস্টমার ৩৬০° সিআরএম ইন্টেলিজেন্স ও ট্যাগিং',
    whatIsThis: 'A single unified dashboard displaying complete lifetime orders, delivery locations, communication history, loyalty tier, internal staff notes, and behavioral tags for any verified buyer.',
    whatIsThisBn: 'যেকোনো গ্রাহকের সামগ্রিক অর্ডার ইতিহাস, ডেলিভারি ঠিকানা, যোগাযোগের তথ্য, অভ্যন্তরীণ নোট এবং কাস্টমার ট্যাগের একটি সমন্বিত প্রোফাইল।',
    whyUsed: 'Enables customer service and operations teams to provide VIP personalized treatment, remember delivery preferences, and handle inquiries with full historical context.',
    whyUsedBn: 'সাপোর্ট এবং ডেলিভারি টিম যাতে প্রতিটি গ্রাহককে ব্যক্তিগত গুরুত্ব দিতে পারে এবং অতীতের রেফারেন্স জেনে দ্রুত সেবা নিশ্চিত করতে পারে।',
    howItWorks: 'Combines relational orders, audit events, and internal staff annotations into a chronological customer journey timeline.',
    howItWorksBn: 'অর্ডার ইতিহাস, যোগাযোগের লগ এবং অ্যাডমিনদের মন্তব্য একত্রিত করে একটি পূর্ণাঙ্গ টাইমলাইন প্রদর্শন করে।',
    connectedTo: ['Customer Directory', 'Order Management Desk', 'Support Operations', 'Audit Logs'],
    connectedToBn: ['কাস্টমার ডিরেক্টরি', 'অর্ডার ম্যানেজমেন্ট ডেস্ক', 'সাপোর্ট অপারেশন', 'অডিট লগ'],
    whatHappensIfChanged: 'Staff can append internal notes or toggle tags (e.g. VIP, HANDLOOM_LOVER, FRAGILE_PACKAGING) instantly.',
    whatHappensIfChangedBn: 'অ্যাডমিনরা যেকোনো সময় নতুন নোট যোগ করতে পারেন অথবা গ্রাহকের ট্যাগ রিয়েল-টাইমে পরিবর্তন করতে পারেন।',
    affects: ['Customer service response context', 'Internal operational notes', 'Segment filtering'],
    affectsBn: ['গ্রাহক সেবার গতি ও মান', 'অভ্যন্তরীণ নোট', 'ফিল্টারিং সুবিধা'],
    doesNotAffect: ['Customer portal frontend view (notes remain strictly confidential to admin)'],
    doesNotAffectBn: ['গ্রাহকের নিজস্ব অ্যাকাউন্ট ভিউ (নোটগুলো সম্পূর্ণ গোপন থাকে)'],
    requirements: ['Authenticated admin or staff session'],
    requirementsBn: ['লগইন করা অ্যাডমিন বা স্টাফ সেশন'],
    currentStatus: 'Active secure customer profile viewer',
    currentStatusBn: 'নিরাপদ কাস্টমার প্রোফাইল ভিউয়ার সক্রিয়',
    riskLevel: 'LOW',
    riskWarning: 'Do not store sensitive payment card details or private credentials in internal CRM notes.',
    riskWarningBn: 'অভ্যন্তরীণ নোটে কখনো গ্রাহকের পাসওয়ার্ড বা সংবেদনশীল পেমেন্ট তথ্য সংরক্ষণ করবেন না।',
    whoCanChange: 'Super Admin, Order Manager, Support Specialist',
    whoCanChangeBn: 'সুপার অ্যাডমিন, অর্ডার ম্যানেজার, সাপোর্ট স্পেশালিস্ট'
  }
};
